# Site settings
title: "MTA Handling Editor"
description: "The only and the best official ingame handling editor for Multi Theft Auto: San Andreas."
url: "http://deltanic.github.io/Hedit"
baseurl: "/Hedit"

# Build settings
markdown: kramdown
permalink: pretty
