# Site settings
title: MTA Handling Editor
email: 
description: "The only and the best official ingame handling editor for Multi Theft Auto: San Andreas."
url: "http://deltanic.github.io/Hedit"

# Build settings
markdown: kramdown
permalink: pretty
